//
//  main.swift
//  Copies what macOS knows about Apple model identifiers into the package.
//
//  Apple files every model it knows under a tag of the class
//  `com.apple.device-model-code`, which is the same place it keeps the picture
//  of the machine, and answers with the name it sells the thing under. Linux
//  has nothing of the kind, and the identifier alone does not carry the
//  product: `Mac16,11` is a Mac mini and `Mac16,12` is a MacBook Air, and only
//  this database says so.
//
//  So it is copied once, here, into a Swift source the package carries. Run it
//  again on a newer macOS to pick up models that did not exist before, and
//  commit what it writes.
//
//      swift Scripts/extract-device-models/main.swift > Sources/AirplayKit/DeviceModelNames.swift
//
//  The identifiers come out of the system's own bundles rather than from a
//  guess at what exists, and the names come out of `UTType`, because a fair
//  number of the declarations carry no description themselves and only the
//  resolved type has one.
//
//  Copyright © 2026 LAYERED. All rights reserved.
//

import Foundation
import UniformTypeIdentifiers

/// Where the system declares the tags.
let bundles = "/System/Library/CoreServices/CoreTypes.bundle/Contents"

/// Every `Info.plist` that might carry a declaration.
func declarationFiles() -> [String] {
    var files = ["\(bundles)/Info.plist"]

    let library = "\(bundles)/Library"
    let contents = (try? FileManager.default.contentsOfDirectory(atPath: library)) ?? []
    for entry in contents where entry.hasSuffix(".bundle") {
        files.append("\(library)/\(entry)/Contents/Info.plist")
    }

    return files
}

/// Every model identifier the system declares a tag for.
func declaredIdentifiers() -> Set<String> {
    var identifiers: Set<String> = []

    for file in declarationFiles() {
        guard let data = FileManager.default.contents(atPath: file),
              let plist = try? PropertyListSerialization.propertyList(from: data, format: nil),
              let root = plist as? [String: Any]
        else { continue }

        let declarations = (root["UTExportedTypeDeclarations"] as? [[String: Any]] ?? [])
            + (root["UTImportedTypeDeclarations"] as? [[String: Any]] ?? [])

        for declaration in declarations {
            guard let tags = declaration["UTTypeTagSpecification"] as? [String: Any],
                  let codes = tags["com.apple.device-model-code"]
            else { continue }

            if let one = codes as? String { identifiers.insert(one) }
            if let several = codes as? [String] { identifiers.formUnion(several) }
        }
    }

    return identifiers
}

/// What the system calls one identifier, or nil where it will not say.
func name(for identifier: String) -> String? {
    let tagClass = UTTagClass(rawValue: "com.apple.device-model-code")
    guard let type = UTType(tag: identifier, tagClass: tagClass, conformingTo: nil),
          type.isDeclared,
          let described = type.localizedDescription,
          !described.isEmpty
    else { return nil }

    return described
}

// MARK: - Writing it out

var named: [(identifier: String, name: String)] = []
for identifier in declaredIdentifiers().sorted() {
    guard let found = name(for: identifier) else { continue }

    named.append((identifier, found))
}

let system = ProcessInfo.processInfo.operatingSystemVersion
let version = "\(system.majorVersion).\(system.minorVersion).\(system.patchVersion)"

print("""
//
//  DeviceModelNames.swift
//  What Apple calls each of its model identifiers.
//
//  Generated by Scripts/extract-device-models, from macOS \(version). Do not
//  edit by hand: run the script again on a newer system and commit what it
//  writes.
//
//  It is carried here rather than asked of the system, so that macOS and Linux
//  answer the same way. The identifier alone does not say what a machine is,
//  since `Mac16,11` is a Mac mini and `Mac16,12` is a MacBook Air, and this
//  table is the only thing that separates them.
//
//  Copyright © 2026 LAYERED. All rights reserved.
//

/// What Apple calls each model identifier it publishes over AirPlay.
///
/// \(named.count) entries, which is every model the system declares a name for.
enum DeviceModelNames {
    /// The name for an identifier, or nil where this table does not carry it.
    ///
    /// - Parameter identifier: A model identifier, such as `AudioAccessory5,1`.
    static func name(for identifier: String) -> String? {
        all[identifier]
    }

    static let all: [String: String] = [
""")

for entry in named {
    let escaped = entry.name.replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
    print("        \"\(entry.identifier)\": \"\(escaped)\",")
}

print("""
    ]
}
""")

FileHandle.standardError.write(Data("\(named.count) of \(declaredIdentifiers().count) identifiers carry a name\n".utf8))
